### ISSUE TITLE
What's the data form, could you provide a simple data sample? 

### ISSUE THREAD

**Issue by chjq201410695** [AnyLeoPeace/DURLECA#1]

**Comment by AnonymousWorld123** [comment]
Hi, the size for the OD data is $T * N * N$. $T$ refers to the time steps. $N$ refers to the number of regions in the city.

**Comment by AnyLeoPeace** [comment]
Hi, the size for the OD data is $T * N * N$. $T$ refers to the time steps. $N$ refers to the number of regions in the city.

**Comment by AnyLeoPeace** [comment]
Element in the $i$-th row, $j$-th column of the $N*N$ matrix denotes for the number of people who move from region $i$ to region $j$.

**Comment by chjq201410695** [comment]
So, the data table contains four columns. The first column is the time step, the second column is the origin area ID (O), the third column is the destination area ID (D), and the fourth column is the number of travelers from O to D？ Right？

**Comment by AnyLeoPeace** [comment]
The OD tensor has 3 dimensions, not 4 dimensions. The first three dimensions are as you described. But we don't need to distinguish exact travelers in an extra dimension.

**Comment by chjq201410695** [comment]
got it！ A 3 dimesion tensor!
