### ISSUE TITLE
How can I be granted to access real-world dataset?

### ISSUE THREAD

**Issue by Lanture1064** [AnyLeoPeace/DURLECA#2]
I've working on my paper recently, during which I have to recurrent a real-world based projection for comparison. How can I be granted to access the data?

**Comment by AnyLeoPeace** [comment]
Hi, I can forward the request to the data owner. Could you please provide your full information, including data use purpose, to the contact email of our paper?

**Comment by Lanture1064** [comment]
Sure, and can I contact the mail posted on https://rlforpandemic.wordpress.com/ ?

**Comment by Sobbbbbber** [comment]
I am interested in your work, which is related to my project. I also want to be granted to access the real-world dataset.
I am looking forward to your reply.
Thanks a lot~
@AnyLeoPeace

**Comment by Sobbbbbber** [comment]
> Hi, I can forward the request to the data owner. Could you please provide your full information, including data use purpose, to the contact email of our paper?

I am interested in your work, which is related to my project. I also want to be granted to access the real-world dataset.
I am looking forward to your reply.
Thanks a lot~
